- id: collectd-ceilometer_install
  type: puppet
  version: 2.0.0
  groups: [compute]
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: puppet/manifests/collectd-ceilometer_install.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720
