attributes:
    enable_mcelog:
      type: "checkbox"
      weight: 20
      value: false
      label: "Enable collectd for mcelog"
    enable_hugepages:
      type: "checkbox"
      weight: 20
      value: false
      label: "Enable collectd for hugepages"
    enable_ovs_events:
      type: "checkbox"
      weight: 20
      value: false
      label: "Enable collectd for Open vSwitch events"
